# Generated by Django 6.0.2 on 2026-02-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField(default='no description available')),
                ('price', models.IntegerField(default=0)),
                ('isOffer', models.BooleanField(default=False)),
            ],
        ),
    ]
